### ISSUE TITLE
InvalidCharacterError: Invalid character

### ISSUE THREAD

**Issue by Trapify-de** [AntonioErdeljac/next13-ai-saas#6]
Installed as readme says. 
Used same provider etc as example + setup all apis properly. 
run npm install and prisma query

on npm run dev this occurs.

Full Error Code:
> next13-ai-saas@0.1.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/Entwicklung/next13-ai-saas/.env
- event compiled client and server successfully in 284 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 75 ms (20 modules)
- wait compiling /middleware (client and server)...
- event compiled successfully in 315 ms (244 modules)
- wait compiling /(landing)/page (client and server)...
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 5.4s (2610 modules)
- event compiled client and server successfully (2596 modules)
- warn Fast Refresh had to perform a full reload due to a runtime error.
- error InvalidCharacterError: Invalid character
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:520:10)
    at atob (node:buffer:1349:13)
    at At (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1177:64)
    at Nr (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1174:55)
    at j (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1165:23)
    at rr (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1916:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/@clerk/nextjs/dist/esm/server/redirect.js:19:104)
    at (sc_server)/./node_modules/@clerk/nextjs/dist/esm/server/redirect.js (/Users//Entwicklung/next13-ai-saas/.next/server/app/(landing)/page.js:3906:1)
    at __webpack_require__ (/Users/Entwicklung/next13-ai-saas/.next/server/webpack-runtime.js:33:43) {
  digest: undefined
}
- wait compiling /favicon.ico/route (client and server)...
- event compiled client and server successfully in 608 ms (2623 modules)
- warn Fast Refresh had to perform a full reload due to a runtime error.
- error InvalidCharacterError: Invalid character
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:520:10)
    at atob (node:buffer:1349:13)
    at At (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1177:64)
    at Nr (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1174:55)
    at j (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1165:23)
    at rr (webpack-internal:///(sc_server)/./node_modules/@clerk/backend/dist/index.js:1916:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/@clerk/nextjs/dist/esm/server/redirect.js:19:104)
    at (sc_server)/./node_modules/@clerk/nextjs/dist/esm/server/redirect.js (/Users/Entwicklung/next13-ai-saas/.next/server/app/(landing)/page.js:3906:1)
    at __webpack_require__ (/Users/Entwicklung/next13-ai-saas/.next/server/webpack-runtime.js:33:43) {
  digest: undefined
}

**Comment by NextThread** [comment]
hey, I'd like to work on this issue
